#!/usr/bin/env python3
"""Script that takes an SKI combinator expression, parses it, prints it back, and evaluates it"""
import sys

from expr import evaluate_expr, parse_expr, expr_to_str

if __name__ == "__main__":
    USAGE_STRING = f"Usage: ./{sys.argv[0]} ski\n"

    if len(sys.argv) != 2:
        sys.stderr.write("ERROR: Wrong number of arguments.")
        sys.stderr.write(USAGE_STRING)
        exit(1)

    expr = parse_expr(sys.argv[1])
    print('Parsed expression:')
    print(expr_to_str(expr))
    print('Evaluation:')
    evaluate_expr(expr, output=True)
